- Homelab:
    - Linkding:
        icon: linkding.png
        href: http://linkding.homelab.internal/
        # siteMonitor: http://linkding.linkding.svc.cluster.local
        target: _self
- AI:
    - ChatGPT:
        icon: chatgpt.png
        href: https://chatgpt.com/
        target: _self
    - AI Fiesta:
        icon: https://chat.aifiesta.ai/static/images/logo/icon.png
        href: https://chat.aifiesta.ai/
        target: _self
    - Gemini:
        icon: google-gemini.png
        href: https://gemini.google.com/app
        target: _self
    - Claude:
        icon: claude-ai.png
        href: https://claude.ai/chats
        target: _self
    - Microsoft Copilot:
        icon: microsoft-copilot.png
        href: https://copilot.microsoft.com
        target: _self
    - GitHub Copilot:
        icon: https://registry.npmmirror.com/@lobehub/icons-static-png/1.62.0/files/light/githubcopilot.png
        href: https://github.com/copilot/
        target: _self
    - Grok:
        icon: grok.png
        href: https://grok.com/
        target: _self
    - Perplexity:
        icon: https://registry.npmmirror.com/@lobehub/icons-static-png/1.62.0/files/light/perplexity-color.png
        href: https://www.perplexity.ai/
        target: _self
